parameters:
  - name: patternSettings
    type: object
  - name: jobSettings
    type: object

jobs:
  - deployment: workload_deployment_${{ parameters.jobSettings.environment }}
    displayName: Azure Deployment
    environment: ${{ parameters.jobSettings.environment }}
    variables:       
      - template: ${{ parameters.patternSettings.configurationFilePath }}/metadata.yml@self
      
      - name: patternArtifactsDirectory        
        value: $(Pipeline.Workspace)/$(deploymentPattern)/      
      - name: iacMainFilePath
        value: $(patternArtifactsDirectory)/iac/${{ parameters.jobSettings.stage.infrastructure.iac.iacMainFileName }}

    strategy:
      runOnce:
        deploy:
          steps:
            # Import values from json files as environment variables from ${{ parameters.patternSettings.configurationFilePath }}/metadata.jsonc
            # Using Install-Module -Name AzureDevOps.Tools -RequiredVersion 0.4.1-alpha -AllowPrerelease
            - powershell: |
                Install-Module -Name AzureDevOps.Tools -AllowPrerelease -Force -Scope CurrentUser
                Import-JsonAsEnvironmentVariables -JsonFilePath '${{ parameters.patternSettings.configurationFilePath }}/metadata.jsonc' -ErrorAction Stop
              displayName: Import JSON configuration as environment variables              

            # Debug step to show settings and environment variables
            # Only runs if System.Debug is set to true
            - powershell: |
                # Shows all configurations for debugging purposes of patternSettings
                Write-Host "Service Connection: '${{ parameters.jobSettings.stage.infrastructure.iac.serviceConnection }}' "
                Write-Host "\nParameters:"
                Write-Host '${{ convertToJson(parameters) }}'
                Write-Host "\nVariables:"
                Get-ChildItem env:

                tree /F $(Pipeline.Workspace)
              displayName: Debug - Display Settings and Environment Variables
              condition: eq( variables['System.Debug'], 'true' )
           
            - task: PowerShell@2 #TODO: Move to dedicated task
              displayName: Replace Config Tokens
              inputs:
                targetType: filePath
                failOnStderr: true
                showWarnings: true
                pwsh: true
                filePath: $(Pipeline.Workspace)/common/scripts/Replace-ConfigurationFilesTokens.ps1                
                arguments: |
                  -ConfigFilesRootFolder '$(patternArtifactsDirectory)/configuration'

            # Runs pre deployment powershell scripts
            - ${{ if ne(parameters.jobSettings.stage.infrastructure.preDeploymentScripts, '') }}:
                - ${{ each script in parameters.jobSettings.stage.infrastructure.preDeploymentScripts }}:
                    - task: AzurePowerShell@5
                      name: ${{ script.name }}
                      displayName: Running script ${{ script.name }}
                      inputs:
                        pwsh: true
                        azureSubscription: ${{ script.serviceConnection }}
                        ScriptType: FilePath
                        ScriptPath: $(patternArtifactsDirectory)/scripts/${{ script.name }}.${{ script.scriptExtension }}
                        azurePowerShellVersion: LatestVersion
                        ScriptArguments: ${{ script.arguments }}
                        workingDirectory: $(Pipeline.Workspace)

            #TODO: Iterate for multi iac
            #IaC deployment
            - ${{ if and(ne(parameters.jobSettings.stage.infrastructure.iac, ''), not(parameters.jobSettings.stage.infrastructure.iac.disabled)) }}:
                - task: AzureResourceManagerTemplateDeployment@3
                  condition:
                  inputs:
                    deploymentScope: ${{ parameters.jobSettings.stage.infrastructure.iac.deploymentScope }}
                    azureResourceManagerConnection: ${{ parameters.jobSettings.stage.infrastructure.iac.serviceConnection }}
                    location: $(deploymentLocation)
                    templateLocation: "Linked artifact"
                    csmFile: $(iacMainFilePath)
                    # TODO: For each stage provide the specific configuration if multiple IaC per stage

                    csmParametersFile: $(patternArtifactsDirectory)/configuration/${{ parameters.jobSettings.stage.infrastructure.iac.iacParameterFileName }}
                    overrideParameters: ${{ parameters.jobSettings.stage.infrastructure.iac.customBicepParameters }}
                    deploymentMode: Incremental
                    deploymentName: ${{ parameters.jobSettings.stage.infrastructure.iac.name }}-app_$(applicationAbbreviation)-$(Build.BuildId)
                    deploymentOutputs: deploymentOutputs
                    ${{ if eq(parameters.jobSettings.stage.infrastructure.iac.deploymentScope, 'ResourceGroup') }}:
                      resourceGroupName: ${{ parameters.jobSettings.stage.infrastructure.iac.resourceGroupName }}
                      subscriptionId: ${{ parameters.jobSettings.stage.infrastructure.iac.subscriptionId }}

            # Runs post deployment powershell scripts
            - ${{ if ne(parameters.jobSettings.stage.infrastructure.postDeploymentScripts, '') }}:
                - ${{ each script in parameters.jobSettings.stage.infrastructure.postDeploymentScripts }}:
                    - task: AzurePowerShell@5
                      name: ${{ script.name }}
                      displayName: Running script ${{ script.name }}
                      inputs:
                        pwsh: true
                        azureSubscription: ${{ script.serviceConnection }}
                        ScriptType: FilePath
                        ScriptPath: $(patternArtifactsDirectory)/scripts/${{ script.name }}.${{ script.scriptExtension }}
                        azurePowerShellVersion: LatestVersion
                        ScriptArguments: ${{ script.arguments }}
                        workingDirectory: $(Pipeline.Workspace)
